# Generated by Django 4.2.2 on 2023-06-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory', models.CharField(max_length=100)),
                ('cid', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('prise', models.DecimalField(decimal_places=3, max_digits=6)),
                ('pid', models.IntegerField()),
                ('date', models.DateField()),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcatagory')),
            ],
        ),
    ]
